// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kapkanXDPKapkanBucket struct {
	_             structs.HostLayout
	LastNs        uint64
	TokensPktQ32  uint64
	TokensByteQ32 uint64
}

type kapkanXDPKapkanConfig struct {
	_                structs.HostLayout
	Generation       uint32
	MapSchemaVersion uint32
	PolicyStride     uint32
	StaticStride     uint32
	StaticCount      uint32
	Flags            uint32
	DryRun           uint8
	DropMalformed    uint8
	FpEnabled        uint8
	Pad              [5]uint8
	FpBurst          uint64
	FpRatePerNsQ32   uint64
}

type kapkanXDPKapkanCounter struct {
	_     structs.HostLayout
	Pkts  uint64
	Bytes uint64
}

type kapkanXDPKapkanFpEvent struct {
	_       structs.HostLayout
	Src     [16]uint8
	Dst     [16]uint8
	Sport   uint16
	Dport   uint16
	IsV6    uint8
	Proto   uint8
	Axis    uint8
	Pad     uint8
	PktLen  uint32
	SnapLen uint32
	Pad2    uint32
	Data    [1536]uint8
}

type kapkanXDPKapkanFpSampler struct {
	_         structs.HostLayout
	LastNs    uint64
	TokensQ32 uint64
}

type kapkanXDPKapkanLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type kapkanXDPKapkanLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type kapkanXDPKapkanPolicyBlock struct {
	_       structs.HostLayout
	N_rules uint32
	Pad     uint32
	Rules   [8]kapkanXDPKapkanRule
}

type kapkanXDPKapkanProfile struct {
	_            structs.HostLayout
	RatePps      uint64
	BurstPps     uint64
	RateBps      uint64
	BurstBps     uint64
	NsPerPkt     uint64
	NsPerByte    uint64
	PktPerNsQ32  uint64
	BytePerNsQ32 uint64
}

type kapkanXDPKapkanRlKeyV4 struct {
	_       structs.HostLayout
	Victim  uint32
	Src     uint32
	Profile uint32
	Pad     uint32
}

type kapkanXDPKapkanRlKeyV6 struct {
	_       structs.HostLayout
	Victim  [16]uint8
	Src     [16]uint8
	Profile uint32
	Pad     uint32
}

type kapkanXDPKapkanRule struct {
	_            structs.HostLayout
	ExpiresAtNs  uint64
	RuleId       uint32
	Profile      uint32
	Src          [16]uint8
	Dst          [16]uint8
	SrcPrefixlen uint8
	DstPrefixlen uint8
	Action       uint8
	Proto        uint8
	TcpFlags     uint8
	TcpFlagsMask uint8
	Flags        uint8
	MatchExt     uint8
	Sport        uint16
	Dport        uint16
	Pad1         uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	kapkanXDPMapKapkanAllow4     = "kapkan_allow4"
	kapkanXDPMapKapkanAllow6     = "kapkan_allow6"
	kapkanXDPMapKapkanCfg        = "kapkan_cfg"
	kapkanXDPMapKapkanFpEvents   = "kapkan_fp_events"
	kapkanXDPMapKapkanFpSampler  = "kapkan_fp_sampler"
	kapkanXDPMapKapkanPolicies   = "kapkan_policies"
	kapkanXDPMapKapkanProfiles   = "kapkan_profiles"
	kapkanXDPMapKapkanProtect4   = "kapkan_protect4"
	kapkanXDPMapKapkanProtect6   = "kapkan_protect6"
	kapkanXDPMapKapkanRlSrc4     = "kapkan_rl_src4"
	kapkanXDPMapKapkanRlSrc6     = "kapkan_rl_src6"
	kapkanXDPMapKapkanRuleStats  = "kapkan_rule_stats"
	kapkanXDPMapKapkanStatics    = "kapkan_statics"
	kapkanXDPMapKapkanStats      = "kapkan_stats"
	kapkanXDPMapKapkanVictims4   = "kapkan_victims4"
	kapkanXDPMapKapkanVictims6   = "kapkan_victims6"
	kapkanXDPProgKapkanXdpFilter = "kapkan_xdp_filter"
)

// loadKapkanXDP returns the embedded CollectionSpec for kapkanXDP.
func loadKapkanXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KapkanXDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kapkanXDP: %w", err)
	}

	return spec, err
}

// loadKapkanXDPObjects loads kapkanXDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kapkanXDPObjects
//	*kapkanXDPPrograms
//	*kapkanXDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKapkanXDPObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadKapkanXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kapkanXDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kapkanXDPSpecs struct {
	kapkanXDPProgramSpecs
	kapkanXDPMapSpecs
	kapkanXDPVariableSpecs
}

// kapkanXDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kapkanXDPProgramSpecs struct {
	KapkanXdpFilter *ebpf.ProgramSpec `ebpf:"kapkan_xdp_filter"`
}

// kapkanXDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kapkanXDPMapSpecs struct {
	KapkanAllow4    *ebpf.MapSpec `ebpf:"kapkan_allow4"`
	KapkanAllow6    *ebpf.MapSpec `ebpf:"kapkan_allow6"`
	KapkanCfg       *ebpf.MapSpec `ebpf:"kapkan_cfg"`
	KapkanFpEvents  *ebpf.MapSpec `ebpf:"kapkan_fp_events"`
	KapkanFpSampler *ebpf.MapSpec `ebpf:"kapkan_fp_sampler"`
	KapkanPolicies  *ebpf.MapSpec `ebpf:"kapkan_policies"`
	KapkanProfiles  *ebpf.MapSpec `ebpf:"kapkan_profiles"`
	KapkanProtect4  *ebpf.MapSpec `ebpf:"kapkan_protect4"`
	KapkanProtect6  *ebpf.MapSpec `ebpf:"kapkan_protect6"`
	KapkanRlSrc4    *ebpf.MapSpec `ebpf:"kapkan_rl_src4"`
	KapkanRlSrc6    *ebpf.MapSpec `ebpf:"kapkan_rl_src6"`
	KapkanRuleStats *ebpf.MapSpec `ebpf:"kapkan_rule_stats"`
	KapkanStatics   *ebpf.MapSpec `ebpf:"kapkan_statics"`
	KapkanStats     *ebpf.MapSpec `ebpf:"kapkan_stats"`
	KapkanVictims4  *ebpf.MapSpec `ebpf:"kapkan_victims4"`
	KapkanVictims6  *ebpf.MapSpec `ebpf:"kapkan_victims6"`
}

// kapkanXDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kapkanXDPVariableSpecs struct {
}

// kapkanXDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKapkanXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type kapkanXDPObjects struct {
	kapkanXDPPrograms
	kapkanXDPMaps
	kapkanXDPVariables
}

func (o *kapkanXDPObjects) Close() error {
	return _KapkanXDPClose(
		&o.kapkanXDPPrograms,
		&o.kapkanXDPMaps,
	)
}

// kapkanXDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKapkanXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type kapkanXDPMaps struct {
	KapkanAllow4    *ebpf.Map `ebpf:"kapkan_allow4"`
	KapkanAllow6    *ebpf.Map `ebpf:"kapkan_allow6"`
	KapkanCfg       *ebpf.Map `ebpf:"kapkan_cfg"`
	KapkanFpEvents  *ebpf.Map `ebpf:"kapkan_fp_events"`
	KapkanFpSampler *ebpf.Map `ebpf:"kapkan_fp_sampler"`
	KapkanPolicies  *ebpf.Map `ebpf:"kapkan_policies"`
	KapkanProfiles  *ebpf.Map `ebpf:"kapkan_profiles"`
	KapkanProtect4  *ebpf.Map `ebpf:"kapkan_protect4"`
	KapkanProtect6  *ebpf.Map `ebpf:"kapkan_protect6"`
	KapkanRlSrc4    *ebpf.Map `ebpf:"kapkan_rl_src4"`
	KapkanRlSrc6    *ebpf.Map `ebpf:"kapkan_rl_src6"`
	KapkanRuleStats *ebpf.Map `ebpf:"kapkan_rule_stats"`
	KapkanStatics   *ebpf.Map `ebpf:"kapkan_statics"`
	KapkanStats     *ebpf.Map `ebpf:"kapkan_stats"`
	KapkanVictims4  *ebpf.Map `ebpf:"kapkan_victims4"`
	KapkanVictims6  *ebpf.Map `ebpf:"kapkan_victims6"`
}

func (m *kapkanXDPMaps) Close() error {
	return _KapkanXDPClose(
		m.KapkanAllow4,
		m.KapkanAllow6,
		m.KapkanCfg,
		m.KapkanFpEvents,
		m.KapkanFpSampler,
		m.KapkanPolicies,
		m.KapkanProfiles,
		m.KapkanProtect4,
		m.KapkanProtect6,
		m.KapkanRlSrc4,
		m.KapkanRlSrc6,
		m.KapkanRuleStats,
		m.KapkanStatics,
		m.KapkanStats,
		m.KapkanVictims4,
		m.KapkanVictims6,
	)
}

// kapkanXDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKapkanXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type kapkanXDPVariables struct {
}

// kapkanXDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKapkanXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type kapkanXDPPrograms struct {
	KapkanXdpFilter *ebpf.Program `ebpf:"kapkan_xdp_filter"`
}

func (p *kapkanXDPPrograms) Close() error {
	return _KapkanXDPClose(
		p.KapkanXdpFilter,
	)
}

func _KapkanXDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kapkanxdp_bpfel.o
var _KapkanXDPBytes []byte
