// YAML emitter. Builds a commented Kapkan config from the wizard state, by hand
// (no YAML dependency) so we control formatting, comments and — crucially — the
// footgun-safe rules: dry_run is always written explicitly (and turning it off
// is a loud, opt-in choice), secrets are emitted as environment-variable NAMES
// never values, and empty optional fields are omitted so the engine applies its
// own defaults.

export type Neighbor = { address: string; remote_asn: string };

export type WizardState = {
  dry_run: boolean;
  sflow: string;
  netflow: string;
  default_rate: string;
  networks: string[];
  whitelist: string[];
  pps: string;
  mbps: string;
  flows_per_sec: string;
  tcp_syn_pps: string;
  udp_pps: string;
  mitigation: string;
  ttl_seconds: string;
  unban_hysteresis_seconds: string;
  max_active_bans: string;
  local_asn: string;
  router_id: string;
  next_hop: string;
  next_hop6: string;
  community: string;
  neighbors: Neighbor[];
  tg_token_env: string;
  tg_chat_id: string;
  api_listen: string;
  api_token_env: string;
  gr_enabled: boolean;
  gr_restart_seconds: string;
  gr_long_lived: boolean;
  gr_long_lived_stale: string;
  state_file: string;
  uc_enabled: boolean;
  uc_interval: string;
  uc_channel: string;
  uc_url: string;
  uc_notify: boolean;
};

export const initialState: WizardState = {
  dry_run: true,
  sflow: ":6343",
  netflow: ":2055",
  default_rate: "1000",
  networks: ["203.0.113.0/24"],
  whitelist: [],
  pps: "80000",
  mbps: "1000",
  flows_per_sec: "35000",
  tcp_syn_pps: "",
  udp_pps: "",
  mitigation: "blackhole",
  ttl_seconds: "600",
  unban_hysteresis_seconds: "120",
  max_active_bans: "50",
  local_asn: "65001",
  router_id: "10.0.0.1",
  next_hop: "192.0.2.1",
  next_hop6: "",
  community: "65000:666",
  neighbors: [{ address: "10.0.0.254", remote_asn: "65000" }],
  tg_token_env: "",
  tg_chat_id: "",
  api_listen: "127.0.0.1:8080",
  api_token_env: "",
  gr_enabled: true,
  gr_restart_seconds: "",
  gr_long_lived: false,
  gr_long_lived_stale: "",
  state_file: "",
  uc_enabled: false,
  uc_interval: "",
  uc_channel: "stable",
  uc_url: "",
  uc_notify: false,
};

const q = (v: string) => `"${v.replace(/"/g, '\\"')}"`;
const num = (v: string) => v.trim();

export function emitConfig(s: WizardState): string {
  const L: string[] = [];
  L.push("# Kapkan configuration — generated by the kapkan.io config builder.");
  L.push("# Validate before going live:  kapkan -check-config kapkan.yaml");
  L.push("");

  if (s.dry_run) {
    L.push("dry_run: true                       # simulated, never announced — keep until detection is validated");
  } else {
    L.push("dry_run: false                      # LIVE: BGP announcements WILL be sent to your neighbors");
  }
  L.push("");

  L.push("listen:");
  L.push(`  sflow: ${q(s.sflow)}`);
  if (s.netflow.trim()) L.push(`  netflow: ${q(s.netflow)}             # NetFlow v5/v9 + IPFIX share this socket`);
  L.push("");

  L.push("sampling:");
  L.push(`  default_rate: ${num(s.default_rate)}                # used when an exporter omits its own rate`);
  L.push("");

  L.push("networks:                             # detection applies only inside these; no overlaps");
  for (const n of s.networks) if (n.trim()) L.push(`  - ${q(n.trim())}`);
  L.push("");

  if (s.whitelist.some((w) => w.trim())) {
    L.push("protected_whitelist:                  # never banned, regardless of traffic");
    for (const w of s.whitelist) if (w.trim()) L.push(`  - ${q(w.trim())}`);
    L.push("");
  }

  L.push("thresholds:                           # per destination host, real (unsampled) units");
  L.push(`  pps: ${num(s.pps)}`);
  L.push(`  mbps: ${num(s.mbps)}`);
  L.push(`  flows_per_sec: ${num(s.flows_per_sec)}`);
  if (s.tcp_syn_pps.trim() && num(s.tcp_syn_pps) !== "0") L.push(`  tcp_syn_pps: ${num(s.tcp_syn_pps)}`);
  if (s.udp_pps.trim() && num(s.udp_pps) !== "0") L.push(`  udp_pps: ${num(s.udp_pps)}`);
  L.push("");

  if (s.mitigation && s.mitigation !== "blackhole") {
    L.push(`mitigation: ${s.mitigation}`);
    L.push("");
  }

  L.push("ban:");
  L.push(`  ttl_seconds: ${num(s.ttl_seconds)}                  # every ban auto-withdraws after this`);
  L.push(`  unban_hysteresis_seconds: ${num(s.unban_hysteresis_seconds)}     # stay below threshold this long before unban`);
  L.push(`  max_active_bans: ${num(s.max_active_bans)}`);
  if (s.state_file.trim()) {
    L.push(`  state_file: ${q(s.state_file.trim())}   # persist active bans across a restart (needs a writable dir; pairs with graceful_restart)`);
  }
  L.push("");

  L.push("bgp:");
  L.push(`  local_asn: ${num(s.local_asn)}`);
  L.push(`  router_id: ${q(s.router_id)}              # must be an IPv4 dotted-quad`);
  L.push(`  next_hop: ${q(s.next_hop)}              # IPv4 blackhole (discard) next-hop`);
  if (s.next_hop6.trim()) L.push(`  next_hop6: ${q(s.next_hop6.trim())}`);
  L.push(`  community: ${q(s.community)}            # RTBH community your upstream honors`);
  L.push("  neighbors:");
  for (const n of s.neighbors) {
    if (!n.address.trim()) continue;
    L.push(`    - address: ${q(n.address.trim())}`);
    L.push(`      remote_asn: ${num(n.remote_asn)}`);
  }
  // graceful_restart: on by default — emit only the knobs the operator changed.
  const gr: string[] = [];
  if (!s.gr_enabled) gr.push("    enabled: false             # opt OUT of Graceful Restart (a restart will then flush routes)");
  if (s.gr_restart_seconds.trim() && num(s.gr_restart_seconds) !== "0") gr.push(`    restart_seconds: ${num(s.gr_restart_seconds)}`);
  if (s.gr_long_lived) gr.push("    long_lived: true");
  if (s.gr_long_lived_stale.trim() && num(s.gr_long_lived_stale) !== "0") gr.push(`    long_lived_stale_seconds: ${num(s.gr_long_lived_stale)}`);
  if (gr.length) {
    L.push("  graceful_restart:");
    for (const g of gr) L.push(g);
  }
  L.push("");

  if (s.tg_token_env.trim()) {
    L.push("notify:");
    L.push("  telegram:");
    L.push(`    token_env: ${q(s.tg_token_env.trim())}     # NAME of the env var holding the bot token — never the token itself`);
    if (s.tg_chat_id.trim()) L.push(`    chat_id: ${q(s.tg_chat_id.trim())}`);
    L.push("");
  }

  if (s.uc_enabled) {
    L.push("update_check:                         # opt-in check for a newer release (no egress unless enabled)");
    L.push("  enabled: true");
    if (s.uc_interval.trim() && num(s.uc_interval) !== "0") L.push(`  interval_seconds: ${num(s.uc_interval)}`);
    if (s.uc_channel && s.uc_channel !== "stable") L.push(`  channel: ${s.uc_channel}`);
    if (s.uc_url.trim()) L.push(`  url: ${q(s.uc_url.trim())}`);
    if (s.uc_notify) L.push("  notify: true                        # also send 'update available' via notify channels");
    L.push("");
  }

  L.push("api:");
  L.push(`  listen: ${q(s.api_listen)}        # default localhost bind needs no auth`);
  if (s.api_token_env.trim()) {
    L.push(`  token_env: ${q(s.api_token_env.trim())}      # REQUIRED before exposing the listener beyond localhost`);
  } else {
    L.push("  # token_env: \"KAPKAN_API_TOKEN\"   # set before exposing the API beyond localhost");
  }

  return L.join("\n") + "\n";
}
